services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $locale: '%locale%'
            $dataCacheDir: '%kernel.cache_dir%/krg/data'
            $webDir: '%kernel.root_dir%/../web'
            $exportSettings: '%krg_core_export_settings%'

    KRG\CoreBundle\Security\Voter\AccessVoter:
        tags: [ 'security.voter' ]

    KRG\CoreBundle\Form\Extension\DateTypeExtension:
        public: true
        tags:
            - { name: 'form.type_extension', extended_type: 'Symfony\Component\Form\Extension\Core\Type\DateType' }

    KRG\CoreBundle\Form\Extension\DateTimeTypeExtension:
        public: true
        tags:
            - { name: 'form.type_extension', extended_type: 'Symfony\Component\Form\Extension\Core\Type\DateTimeType' }

    KRG\CoreBundle\Form\Type\:
        resource: '../../Form/Type'
        tags: ['form.type']

    KRG\CoreBundle\Export\:
        resource: '../../Export/*Export.php'
        public: true

    KRG\CoreBundle\Model\:
        resource: '../../Model/*'
        exclude: '../../Model/{ModelView,ModelPath}.php'
        public: true
        tags: ['krg.model']

    KRG\CoreBundle\Serializer\:
        resource: '../../Serializer'
        public: true

    KRG\CoreBundle\Twig\:
        resource: '../../Twig'
        tags:
            - { name: twig.extension }

    Twig_Extensions_Extension_Intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
